import type {Metadata} from "next";
import {Arrow,ContactBand,Eyebrow,TransitionLink,VideoHero,Words} from "../components/Sections";
export const metadata:Metadata={title:"Website services",description:"Clear website packages and a collaborative process built for startups and growing businesses."};
const packages=[
 {name:"Launch Page",for:"Founders · Single offers",copy:"A focused one-page experience for launching quickly with the message, design and technical quality already in place.",items:["Discovery and positioning","Custom responsive design","Performance-first development","Analytics and launch support"]},
 {name:"Brand Website",for:"Growing service businesses",copy:"A structured multi-page website that explains what you do, builds trust and gives every audience a clear next action.",items:["Information architecture","Custom visual system","CMS and integrations","SEO and measurement"]},
 {name:"Commerce Lite",for:"Stores · Product brands",copy:"A refined commerce experience that is easy to browse, easy to buy from and straightforward for your team to manage.",items:["Product and category UX","Secure checkout","Inventory workflow","Conversion optimisation"]},
 {name:"Scalable Build",for:"Platforms · Complex needs",copy:"A tailored website or digital system designed around custom content, workflows, integrations and future growth.",items:["Product discovery","UX system and prototypes","Scalable engineering","Ongoing delivery partnership"]}
];
const steps=[["01","Discovery","Goals, users and constraints."],["02","Direction","Positioning, structure and visual territory."],["03","Design","Responsive screens and working prototypes."],["04","Build","Production engineering and integrations."],["05","Quality","Content, accessibility and device testing."],["06","Release","Launch, measurement and support."]];
export default function Services(){return <main><VideoHero video="/videos/services.mp4" kicker="WEBSITE SERVICES" title="The right website for where your business is going." copy="Clear scope, honest timelines and a design-led process that keeps the work focused from discovery to launch."><TransitionLink href="/contact" className="hero-text-link">Discuss your website <Arrow/></TransitionLink></VideoHero>
<section className="package-section section-pad" data-nav-theme="light"><Eyebrow index="01" label="Website packages"/><div className="package-stack">{packages.map((p,i)=><article key={p.name} className={`service-package tone-${i}`} data-reveal><div className="package-number">0{i+1}</div><div><span>{p.for}</span><h2>{p.name}</h2><p>{p.copy}</p><TransitionLink href="/contact" className="line-link">Start a conversation <Arrow/></TransitionLink></div><ul>{p.items.map((x,j)=><li key={x}><span>0{j+1}</span>{x}</li>)}</ul></article>)}</div></section>
<section className="process-section section-pad" data-nav-theme="dark"><Eyebrow index="02" label="A simple process" light/><h2><Words>Structured enough to stay clear. Flexible enough to make the work better.</Words></h2><div className="process-grid">{steps.map(([n,t,c])=><article key={n} data-reveal><span>{n}</span><h3>{t}</h3><p>{c}</p><i/></article>)}</div></section>
<section className="faq-section section-pad" data-nav-theme="light"><Eyebrow index="03" label="Frequently asked"/><div className="faq-layout"><h2><Words>Useful answers before we begin.</Words></h2><div>{[["How long will it take?","Focused launch pages can take around one week. Larger websites generally take four to six weeks, depending on content and complexity."],["Can you handle commerce?","Yes. We design and build clear storefronts, product systems and secure checkout experiences."],["What if the direction is unclear?","That is what discovery is for. We use references, positioning and early prototypes to make the direction tangible before full design begins."],["Are revisions included?","Yes. Review and refinement are built into the design stages so the approved direction is intentional, not rushed."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section><ContactBand/></main>}
