import type {Metadata} from "next";
import {Arrow,ContactBand,Eyebrow,ProcessVisual,TransitionLink,VideoHero,Words} from "../components/Sections";
import {FaqAccordion} from "../components/FaqAccordion";
export const metadata:Metadata={title:"Website services",description:"Clear website packages and a collaborative process built for startups and growing businesses."};
const packages=[
 {name:"Landing Pages",for:"Founders · Single offers",copy:"A focused one-page experience for launching quickly — message, design, and technical quality already in place.",items:["Discovery and positioning","Custom responsive design","Performance-first development","Analytics and launch support"]},
 {name:"Stores",for:"Product brands · Growing retailers",copy:"A refined commerce experience that's easy to browse, easy to buy from, and straightforward for your team to run — yours to own.",items:["Product and category UX","Secure checkout","Inventory workflow","Conversion optimisation"]},
 {name:"Systems",for:"Websites · Platforms · Complex needs",copy:"When the idea is bigger than a single page — structured websites, custom platforms, apps, and digital systems built around your content, workflows, and future growth.",items:["Information architecture and product discovery","Custom visual system and prototypes","CMS, integrations, and scalable engineering","SEO, measurement, and ongoing delivery"]}
];
const steps=[["01","Discovery","Goals, users and constraints.","discovery"],["02","Direction","Positioning, structure and visual territory.","direction"],["03","Design","Responsive screens and working prototypes.","design"],["04","Build","Production engineering and integrations.","build"],["05","Quality","Content, accessibility and device testing.","quality"],["06","Deploy","Launch, measurement and support.","release"]];
export default function Services(){return <main><VideoHero video="/videos/video-3.mp4" kicker="WEBSITE SERVICES" title="The right website for where your business is going." copy="Clear scope, honest timelines and a design-led process that keeps the work focused from discovery to launch."><TransitionLink href="/contact" className="hero-text-link">Discuss your website <Arrow/></TransitionLink></VideoHero>
<section className="package-section section-pad" data-nav-theme="light"><Eyebrow index="01" label="Ways to work"/><div className="package-stack">{packages.map((p,i)=><article key={p.name} className={`service-package tone-${i}`} data-reveal><div className="package-number">0{i+1}</div><div><span>{p.for}</span><h2>{p.name}</h2><p>{p.copy}</p><TransitionLink href="/contact" className="line-link">Start a conversation <Arrow/></TransitionLink></div><ul>{p.items.map((x,j)=><li key={x}><span>0{j+1}</span>{x}</li>)}</ul></article>)}</div></section>
<section className="process-section section-pad" data-nav-theme="dark"><Eyebrow index="02" label="A simple process" light/><h2><Words>Structured enough to stay clear. Flexible enough to make the work better.</Words></h2><div className="process-grid">{steps.map(([n,t,c,v])=><article key={n} data-reveal><span>{n}</span><ProcessVisual kind={v}/><h3>{t}</h3><p>{c}</p><i/></article>)}</div></section>
<section className="faq-section section-pad" data-nav-theme="light"><Eyebrow index="03" label="Frequently asked"/><div className="faq-layout"><h2><Words>Useful answers before we begin.</Words></h2><FaqAccordion items={[["How long will it take?","Focused landing pages can take around a week. Larger websites and systems generally run four to eight weeks, depending on content and complexity."],["Can you handle commerce?","Yes. We design and build clear storefronts, product systems and secure checkout experiences."],["What if the direction is unclear?","That is what discovery is for. We use references, positioning and early prototypes to make the direction tangible before full design begins."],["Are revisions included?","Yes. Review and refinement are built into the design stages so the approved direction is intentional, not rushed."]]}/></div></section><ContactBand/></main>}
