export type OfferVisualKind="launch"|"commerce"|"systems";

function DemoHeader({label,mark}:{label:string;mark:string}){return <div className="demo-header"><span className="demo-mark">{mark}</span><strong>{label}</strong><span className="demo-live">Live</span></div>}

function LaunchVisual(){return <div className="offer-demo" data-demo="launch" aria-hidden="true"><DemoHeader label="Landing page" mark="01"/><div className="demo-browser"><div className="demo-url"><i/><i/><i/><span data-demo-type="yourbrand.com">yourbrand.com</span></div><div className="launch-screen"><div className="launch-copy-col"><small data-demo-item>One clear promise</small><strong data-demo-item>Make the next move obvious.</strong><p className="launch-copy" data-demo-item>One focused page that turns a visitor into a customer.</p><span className="demo-button" data-demo-item>Start a project<i className="demo-ripple"/></span></div><div className="launch-art" data-demo-item><span className="launch-chip">+128%</span><span className="launch-bars"><b/><b/><b/><b/><b/></span></div><span className="demo-cursor"/></div></div><div className="demo-status"><span><i data-demo-pulse/>Ready to launch</span></div></div>}

function CommerceVisual(){return <div className="offer-demo" data-demo="commerce" aria-hidden="true"><DemoHeader label="Storefront" mark="02"/><div className="commerce-flow"><div className="commerce-product" data-demo-item><span className="commerce-thumb"><em/></span><div><strong>Featured product</strong><span className="commerce-rating"><u/><u/><u/><u/><u/>4.9</span><span className="commerce-price">$48<s>$60</s></span></div><b className="commerce-add">+</b></div><div className="commerce-step" data-demo-item><span>01</span><strong>Added to cart</strong><i>✓</i></div><div className="commerce-step" data-demo-item><span>02</span><strong>Secure checkout</strong><i>✓</i></div><div className="commerce-step is-final" data-demo-item><span>03</span><strong>Order confirmed</strong><i>✓</i></div><span className="commerce-fly"/></div><div className="demo-status"><span><i data-demo-pulse/>Friction removed</span></div></div>}

const systemNodes:string[][]=[["Web app","Dashboard","API"],["Client portal","Mobile app","Auth"],["Automations","Payments","CRM"],["Analytics","CMS","Inventory"]];
const systemNodePos=[[16,15],[84,15],[16,85],[84,85]];
function SystemsVisual(){return <div className="offer-demo" data-demo="systems" aria-hidden="true"><DemoHeader label="Product system" mark="03"/><div className="system-map"><svg className="system-lines" viewBox="0 0 100 100" preserveAspectRatio="none">{systemNodePos.map(([x,y],i)=><line key={i} x1="50" y1="50" x2={x} y2={y} pathLength={1}/>)}</svg><i className="system-ring"/><i className="system-ring"/>{systemNodes.map((labels,i)=><span className="system-node" key={i}><span className="node-track">{labels.map(l=><b key={l}>{l}</b>)}<b>{labels[0]}</b></span></span>)}<span className="system-packet"/><span className="system-packet"/><span className="system-packet"/><span className="system-packet"/><div className="system-core" data-demo-pulse>Core</div></div><div className="system-health" data-demo-item><span><i/>All systems connected</span><strong>Stable</strong></div></div>}

export function OfferVisual({kind}:{kind:OfferVisualKind}){if(kind==="launch")return <LaunchVisual/>;if(kind==="commerce")return <CommerceVisual/>;return <SystemsVisual/>}
