export type OfferVisualKind="launch"|"brand"|"commerce"|"scalable";

function DemoHeader({label,mark}:{label:string;mark:string}){return <div className="demo-header"><span className="demo-mark">{mark}</span><strong>{label}</strong><span className="demo-live" data-demo-item>Live</span></div>}

function LaunchVisual(){return <div className="offer-demo" data-demo="launch" aria-hidden="true"><DemoHeader label="Launch page" mark="01"/><div className="demo-browser"><div className="demo-url"><i/><i/><i/><span>yourbrand.com</span></div><div className="launch-screen"><small data-demo-item>One clear promise</small><strong data-demo-item>Make the next move obvious.</strong><div className="launch-copy" data-demo-item><i/><i/></div><span className="demo-button" data-demo-item>Start a project</span></div></div><div className="demo-status"><span><i data-demo-pulse/>Ready to launch</span><b data-demo-bar/></div></div>}

function BrandVisual(){return <div className="offer-demo" data-demo="brand" aria-hidden="true"><DemoHeader label="Site structure" mark="02"/><div className="brand-map"><div className="brand-root" data-demo-item>Brand website</div><div className="brand-rail" data-demo-bar/><div className="brand-pages"><span data-demo-item>Home</span><span data-demo-item>Services</span><span data-demo-item>Proof</span><span data-demo-item>Contact</span></div></div><div className="brand-system" data-demo-item><span>Clear hierarchy</span><div><i/><i/><i/><i/></div></div></div>}

function CommerceVisual(){return <div className="offer-demo" data-demo="commerce" aria-hidden="true"><DemoHeader label="Buying journey" mark="03"/><div className="commerce-flow"><div className="commerce-product" data-demo-item><span className="product-image"/><div><strong>Featured product</strong><small>Ready to order</small></div><b>+</b></div><div className="commerce-step" data-demo-item><span>01</span><strong>Added to cart</strong><i>✓</i></div><div className="commerce-step" data-demo-item><span>02</span><strong>Secure checkout</strong><i>✓</i></div><div className="commerce-step is-final" data-demo-item><span>03</span><strong>Order confirmed</strong><i data-demo-pulse>✓</i></div></div><div className="demo-status"><span>Friction removed</span><b data-demo-bar/></div></div>}

function ScalableVisual(){return <div className="offer-demo" data-demo="scalable" aria-hidden="true"><DemoHeader label="Product system" mark="04"/><div className="system-map"><div className="system-core" data-demo-pulse>Core</div><div className="system-path horizontal" data-demo-bar/><div className="system-path vertical" data-demo-bar/><span data-demo-item>Content API</span><span data-demo-item>Client portal</span><span data-demo-item>Analytics</span><span data-demo-item>Automations</span></div><div className="system-health" data-demo-item><span><i/>All systems connected</span><strong>Stable</strong></div></div>}

export function OfferVisual({kind}:{kind:OfferVisualKind}){if(kind==="launch")return <LaunchVisual/>;if(kind==="brand")return <BrandVisual/>;if(kind==="commerce")return <CommerceVisual/>;return <ScalableVisual/>}
