import {TransitionLink} from "./SiteFrame";
export {TransitionLink,CalendlyLink} from "./SiteFrame";

export const projectData={
 "oyo-eats":{name:"OYO Eats",tag:"Food delivery",url:"oyoeats.lk",logo:"/logos/oyo-eats.png",tone:"lime",summary:"A custom delivery platform connecting local restaurants with customers through a fast, intuitive ordering experience.",challenge:"Turn a growing restaurant operation into a clear digital journey without slowing customers down at the point of choice.",solution:"We created a mobile-first ordering architecture, focused product discovery and a visual system that keeps food, availability and delivery status easy to understand.",metrics:[["45%","Increase in orders"],["3.2×","Faster load times"],["98%","Customer satisfaction"]],shots:["/case-studies/oyo-eats/shot-1.png","/case-studies/oyo-eats/shot-2.png","/case-studies/oyo-eats/shot-3.png","/case-studies/oyo-eats/shot-4.png"]},
 taanz:{name:"Taanz",tag:"Accounting services",url:"taanzoutsourcing.com",logo:"/logos/taanz.png",tone:"blue",summary:"A credible, structured digital presence for an accounting company serving businesses that need clarity and trust.",challenge:"Present a broad financial service offering without making the site feel dense, corporate or difficult to navigate.",solution:"We organised services around client needs, introduced a calm editorial hierarchy and designed a conversion path that makes expertise visible before asking for contact.",metrics:[["78%","Lead generation"],["5.1×","Page views"],["94%","Trust score"]],shots:["/case-studies/taanz/shot-1.png","/case-studies/taanz/shot-2.png","/case-studies/taanz/shot-3.png","/case-studies/taanz/shot-4.png"]},
 nuzii:{name:"Nuzii",tag:"Fashion commerce",url:"nuzii.co",logo:"/logos/nuzi.png",tone:"rose",summary:"A modern commerce experience pairing a refined fashion identity with simple browsing and responsive checkout.",challenge:"Create a store that feels like a distinct fashion brand while keeping product discovery and checkout fast on mobile.",solution:"We built an editorial storefront, simplified category movement and created reusable product storytelling modules that support new collections.",metrics:[["120%","Sales increase"],["2.8×","Conversion rate"],["91%","Customer retention"]],shots:["/case-studies/nuzii/shot-1.png","/case-studies/nuzii/shot-2.png","/case-studies/nuzii/shot-3.png","/case-studies/nuzii/shot-4.png"]},
 noora:{name:"Noora Modesty",tag:"Online store",url:"nooramodesty.com",logo:"/logos/noora-modesty.png",tone:"rose",summary:"A modest-fashion label moved out of Instagram DMs into an editorial storefront built to sell like the brands it looks up to.",challenge:"Turn a loyal Instagram following for abayas, tops and co-ords into a minimal, image-driven storefront that sells on visuals first.",solution:"We built a restrained storefront wired to Clickom so orders flow into one system, stock stays synced by product ID, and product reveals feel premium without getting in the way.",metrics:[["3.6×","Faster order handling"],["99%","Stock sync accuracy"],["1 system","Orders and stock, unified"]],shots:["/case-studies/noora-modesty/shot-1v3.jpg","/case-studies/noora-modesty/shot-2.jpg","/case-studies/noora-modesty/shot-3.jpg","/case-studies/noora-modesty/shot-4.jpg"]},
 forte:{name:"Forte Clinical Laboratories",tag:"Web redesign",url:"fortecl.ae",logo:"/logos/forte-logo.png",tone:"blue",summary:"A six-year-old lab site rebuilt to look and work like the diagnostics leader behind it.",challenge:"Replace a dated Covid-era site with a clean, credible clinical experience that makes Forte’s services easier to find and trust.",solution:"We rebuilt the site around a proper test catalogue and booking flow, with calm motion, clearer structure and the full diagnostic menu up front.",metrics:[["6 yrs","Site rebuilt"],["5000+","Tests surfaced"],["Online","Booking flow"]],shots:["/case-studies/forte-cl/shot-1.jpg","/case-studies/forte-cl/shot-2.jpg","/case-studies/forte-cl/shot-3.jpg","/case-studies/forte-cl/shot-4.jpg"]}
};
export type ProjectKey=keyof typeof projectData;
export function Arrow(){return <span className="ui-arrow" aria-hidden><i /></span>}
export function Words({children}:{children:string}){return <span data-words aria-label={children}>{children.split(" ").map((w,i)=><span className="clip" aria-hidden key={i}><span className="word">{w}&nbsp;</span></span>)}</span>}
export function Eyebrow({index: _index,label: _label,light: _light}:{index:string;label:string;light?:boolean}){return null}
export function VideoHero({video,kicker,title,copy,children}:{video:string;kicker:string;title:string;copy:string;children?:React.ReactNode}){return <section className="page-hero" id="top" data-nav-theme="hero"><video key={video} autoPlay muted loop playsInline preload="metadata"><source src={video} type="video/mp4"/></video><div className="media-scrim"/><div className="hero-grid"/><div className="hero-kicker"><span>{kicker}</span></div><div className="page-hero-content"><h1><Words>{title}</Words></h1><p data-reveal>{copy}</p>{children}</div><div className="hero-index">{"// SCROLL TO EXPLORE"} <i/></div></section>}
export function ProjectCard({slug,large=false,showWebsite=false}:{slug:ProjectKey;large?:boolean;showWebsite?:boolean}){const p=projectData[slug];return <article className={`project-card project-card-${slug} ${p.tone} ${large?"is-large":""}`}><div className="project-card-top"><span>{"// "}{p.tag}</span><span>{p.url}</span></div><div className="project-stage"><div className="browser-frame"><div><i/><i/><i/><small>{p.url}</small></div><img className={p.name==="Forte Clinical Laboratories"?"case-logo-dark":""} src={p.logo} alt={`${p.name} logo`}/></div></div><div className="project-card-bottom"><div><h3>{p.name}</h3><p>{p.summary}</p></div><div className="project-actions"><TransitionLink href={`/portfolio/${slug}`} className="project-link"><span>View case</span><Arrow/></TransitionLink>{showWebsite&&<a href={`https://${p.url}`} className="project-link project-site-link" target="_blank" rel="noopener noreferrer"><span>Visit website</span><Arrow/></a>}</div></div></article>}
export function ProcessVisual({kind}:{kind:string}){const common={viewBox:"0 0 240 120",fill:"none",xmlns:"http://www.w3.org/2000/svg"};return <div className={`process-visual visual-${kind}`} aria-hidden="true"><svg {...common}>
 {kind==="discovery"&&<><circle className="pv-a" cx="120" cy="60" r="17"/><circle className="pv-b" cx="120" cy="60" r="34"/><circle className="pv-c" cx="120" cy="60" r="51"/><circle className="pv-accent pv-dot" cx="120" cy="60" r="4"/></>}
 {kind==="direction"&&<><path className="pv-a" d="M24 28H78C98 28 98 60 120 60H216"/><path className="pv-b" d="M24 92H78C98 92 98 60 120 60"/><path className="pv-c" d="M24 60H216"/><circle className="pv-accent pv-dot" cx="120" cy="60" r="4"/></>}
 {kind==="design"&&<><rect className="pv-a" x="34" y="24" width="76" height="72"/><rect className="pv-b" x="130" y="24" width="76" height="30"/><rect className="pv-c" x="130" y="66" width="76" height="30"/><path className="pv-accent" d="M46 38H98M46 49H82M142 38H191M142 80H184"/></>}
 {kind==="build"&&<><rect className="pv-build-frame" x="42" y="22" width="156" height="76"/><path className="pv-build-header" d="M42 40H198"/><circle className="pv-build-light pv-a" cx="54" cy="31" r="3"/><circle className="pv-build-light pv-b" cx="64" cy="31" r="3"/><circle className="pv-build-light pv-c" cx="74" cy="31" r="3"/><rect className="pv-build-row pv-row-1" x="58" y="52" width="80" height="7"/><rect className="pv-build-row pv-row-2" x="58" y="66" width="116" height="7"/><rect className="pv-build-row pv-row-3 pv-accent" x="58" y="80" width="66" height="7"/></>}
 {kind==="quality"&&<><rect className="pv-quality-sheet" x="54" y="20" width="132" height="80"/><path className="pv-quality-line" d="M80 42H164M80 60H164M80 78H164"/><path className="pv-quality-check pv-a pv-accent" d="M62 42L68 48L77 36"/><path className="pv-quality-check pv-b pv-accent" d="M62 60L68 66L77 54"/><path className="pv-quality-check pv-c pv-accent" d="M62 78L68 84L77 72"/></>}
 {kind==="release"&&<><rect className="pv-live-window" x="38" y="22" width="164" height="76"/><path className="pv-live-header" d="M38 42H202"/><circle className="pv-live-dot" cx="51" cy="32" r="3"/><circle className="pv-live-dot" cx="61" cy="32" r="3"/><circle className="pv-live-dot" cx="71" cy="32" r="3"/><rect className="pv-live-track" x="56" y="55" width="128" height="5"/><rect className="pv-live-progress pv-accent" x="56" y="55" width="128" height="5"/><rect className="pv-live-badge" x="126" y="70" width="58" height="17"/><text className="pv-live-text" x="155" y="82">LIVE</text></>}
 </svg></div>}
export function ContactBand({title}:{title?:string}){return <section className="contact-band" data-nav-theme="dark"><span>{"// NEXT STEP"}</span><h2><Words>{title||"Let’s build something that earns attention."}</Words></h2></section>}
