import {TransitionLink} from "./SiteFrame";
export {TransitionLink} from "./SiteFrame";

export const projectData={
 "oyo-eats":{name:"OYO Eats",tag:"Food delivery",url:"oyoeats.lk",logo:"/logos/oyo-eats.png",tone:"lime",summary:"A custom delivery platform connecting local restaurants with customers through a fast, intuitive ordering experience.",challenge:"Turn a growing restaurant operation into a clear digital journey without slowing customers down at the point of choice.",solution:"We created a mobile-first ordering architecture, focused product discovery and a visual system that keeps food, availability and delivery status easy to understand.",metrics:[["45%","Increase in orders"],["3.2×","Faster load times"],["98%","Customer satisfaction"]]},
 taanz:{name:"Taanz",tag:"Accounting services",url:"taanzoutsourcing.com",logo:"/logos/taanz.png",tone:"blue",summary:"A credible, structured digital presence for an accounting company serving businesses that need clarity and trust.",challenge:"Present a broad financial service offering without making the site feel dense, corporate or difficult to navigate.",solution:"We organised services around client needs, introduced a calm editorial hierarchy and designed a conversion path that makes expertise visible before asking for contact.",metrics:[["78%","Lead generation"],["5.1×","Page views"],["94%","Trust score"]]},
 nuzii:{name:"Nuzii",tag:"Fashion commerce",url:"nuzii.co",logo:"/logos/nuzi.png",tone:"rose",summary:"A modern commerce experience pairing a refined fashion identity with simple browsing and responsive checkout.",challenge:"Create a store that feels like a distinct fashion brand while keeping product discovery and checkout fast on mobile.",solution:"We built an editorial storefront, simplified category movement and created reusable product storytelling modules that support new collections.",metrics:[["120%","Sales increase"],["2.8×","Conversion rate"],["91%","Customer retention"]]},
 noora:{name:"Noora Modesty",tag:"Online store",url:"nooramodesty.com",logo:"/logos/noora-modesty.png",tone:"rose",summary:"A modest-fashion label moved out of Instagram DMs into an editorial storefront built to sell like the brands it looks up to.",challenge:"Turn a loyal Instagram following for abayas, tops and co-ords into a minimal, elevated storefront inspired by Zara.",solution:"We built a restrained storefront wired to Clickom so orders flow into one system, stock stays synced by product ID and product reveals feel premium without getting in the way.",metrics:[["24/7","Storefront availability"],["3.6×","Faster order handling"],["99%","Stock sync accuracy"]]},
 forte:{name:"Forte Clinical Laboratories",tag:"Web redesign",url:"fortecl.ae",logo:"/logos/forte-logo.png",tone:"blue",summary:"A six-year-old lab site rebuilt to look and work like the diagnostics leader behind it.",challenge:"Replace a dated Covid-era site with a clean, credible clinical experience that makes Forte’s services easier to find and trust.",solution:"We rebuilt the site around a proper test catalogue and booking flow, with calm motion, clearer structure and the full diagnostic menu up front.",metrics:[["6 yrs","Site rebuilt"],["5000+","Tests surfaced"],["Online","Booking flow"]]}
};
export type ProjectKey=keyof typeof projectData;
export function Arrow(){return <span className="ui-arrow" aria-hidden><i /></span>}
export function Words({children}:{children:string}){return <span data-words aria-label={children}>{children.split(" ").map((w,i)=><span className="clip" aria-hidden key={i}><span className="word">{w}&nbsp;</span></span>)}</span>}
export function Eyebrow({index: _index,label: _label,light: _light}:{index:string;label:string;light?:boolean}){return null}
export function VideoHero({video,kicker,title,copy,children}:{video:string;kicker:string;title:string;copy:string;children?:React.ReactNode}){return <section className="page-hero" id="top" data-nav-theme="hero"><video key={video} autoPlay muted loop playsInline preload="metadata"><source src={video} type="video/mp4"/></video><div className="media-scrim"/><div className="hero-grid"/><div className="hero-kicker"><span>{kicker}</span></div><div className="page-hero-content"><h1><Words>{title}</Words></h1><p data-reveal>{copy}</p>{children}</div><div className="hero-index">{"// SCROLL TO EXPLORE"} <i/></div></section>}
export function ProjectCard({slug,large=false,showWebsite=false}:{slug:ProjectKey;large?:boolean;showWebsite?:boolean}){const p=projectData[slug];return <article className={`project-card project-card-${slug} ${p.tone} ${large?"is-large":""}`}><div className="project-card-top"><span>{"// "}{p.tag}</span><span>{p.url}</span></div><div className="project-stage"><div className="browser-frame"><div><i/><i/><i/><small>{p.url}</small></div><img className={p.name==="Forte Clinical Laboratories"?"case-logo-dark":""} src={p.logo} alt={`${p.name} logo`}/></div></div><div className="project-card-bottom"><div><h3>{p.name}</h3><p>{p.summary}</p></div><div className="project-actions"><TransitionLink href={`/portfolio/${slug}`} className="project-link"><span>View case</span><Arrow/></TransitionLink>{showWebsite&&<a href={`https://${p.url}`} className="project-link project-site-link" target="_blank" rel="noopener noreferrer"><span>Visit website</span><Arrow/></a>}</div></div></article>}
export function ContactBand({title="Let’s build something that earns attention."}:{title?:string}){return <section className="contact-band" data-nav-theme="dark"><span>{"// NEXT STEP"}</span><h2><Words>{title}</Words></h2><TransitionLink href="/contact" className="band-link">Start a project <Arrow/></TransitionLink></section>}
