import type {Metadata} from "next";
import {ContactBand,Eyebrow,VideoHero,Words} from "../components/Sections";
export const metadata:Metadata={title:"About",description:"Forty Pixels is a focused design and development studio for founders and growing businesses."};
const values=[["Effortless clarity","Good design guides people without making them work for the answer."],["Speed with purpose","Moving quickly matters when every decision still supports the goal."],["Direct communication","The people in the conversation are the people doing the work."],["Every screen","Mobile, tablet and desktop are designed as one connected experience."],["Accessible quality","Premium work comes from focus and craft—not unnecessary layers."],["Long-term thinking","A website or product should be able to grow with the business behind it."]];
const valueIcons=[
 <svg key="clarity" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7Z"/></svg>,
 <svg key="speed" viewBox="0 0 24 24" aria-hidden="true"><path d="M13 2 4 14h6l-1 8 9-12h-6l1-8Z"/></svg>,
 <svg key="comms" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v11H9l-5 4V5Z"/><path d="M8 9h8M8 12.5h5"/></svg>,
 <svg key="screens" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="14" height="10" rx="1"/><path d="M7 20h6"/><rect x="16" y="9" width="5" height="9" rx="1"/></svg>,
 <svg key="quality" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 4 5v6c0 5 3.5 8.5 8 9 4.5-.5 8-4 8-9V5l-8-3Z"/><path d="M9 12l2 2 4-4"/></svg>,
 <svg key="growth" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 17 10 11 14 15 20 6"/><path d="M14 6h6v6"/></svg>,
];
export default function About(){return <main><VideoHero video="/videos/video-2.mp4" kicker="ABOUT FORTY PIXELS" title="Small enough to stay close. Experienced enough to see the whole system." copy="We are a design and development studio helping founders, new businesses and growing brands build a confident digital presence."/>
<section className="story section-pad" data-nav-theme="light"><Eyebrow index="01" label="Who we are"/><div className="story-layout"><h2><Words>We make ambitious digital work feel understandable.</Words></h2><div data-reveal><p>Many clients arrive with an outdated website, a product idea that is difficult to explain or a digital experience that no longer matches the business.</p><p>We make the path forward clear. Strategy, design and development stay connected, communication remains direct and every major decision is visible before it becomes expensive.</p></div></div></section>
<section className="mission section-pad" data-nav-theme="lime"><Eyebrow index="02" label="Our mission"/><h2><Words>Give growing businesses access to digital quality without agency complexity.</Words></h2><p data-reveal>Clean thinking. Fast delivery. A collaborative workflow. Work that earns trust and supports long-term growth.</p></section>
<section className="values section-pad" data-nav-theme="light"><Eyebrow index="03" label="Principles behind the work"/><div className="values-grid">{values.map(([t,c],i)=><article key={t} data-reveal><span>0{i+1}</span><div className="values-icon">{valueIcons[i]}</div><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section className="belief section-pad" data-nav-theme="dark"><Eyebrow index="04" label="What clients get" light/><blockquote data-reveal>One focused team, one clear direction and a digital experience built around what the business needs next.</blockquote></section><ContactBand/></main>}
