import type {Metadata} from "next";
import {ContactBand,Eyebrow,VideoHero,Words} from "../components/Sections";
export const metadata:Metadata={title:"About",description:"Forty Pixels is a focused design and development studio for founders and growing businesses."};
const values=[["Effortless clarity","Good design guides people without making them work for the answer."],["Speed with purpose","Moving quickly matters when every decision still supports the goal."],["Direct communication","The people in the conversation are the people doing the work."],["Every screen","Mobile, tablet and desktop are designed as one connected experience."],["Accessible quality","Premium work comes from focus and craft—not unnecessary layers."],["Long-term thinking","A website or product should be able to grow with the business behind it."]];
const valueIcons=[
 <svg key="clarity" viewBox="0 0 64 64" aria-hidden="true"><path className="ico-line" d="M32 14c14 0 24 12 26 18-2 6-12 18-26 18S8 38 6 32c2-6 12-18 26-18Z"/><circle className="ico-line" cx="32" cy="32" r="9"/><circle className="ico-dot" cx="32" cy="32" r="3"/></svg>,
 <svg key="speed" viewBox="0 0 64 64" aria-hidden="true"><path className="ico-fill ico-line ico-thin" strokeLinejoin="round" d="M36 6 14 36h14l-4 22 22-30H32l4-22Z"/></svg>,
 <svg key="comms" viewBox="0 0 64 64" aria-hidden="true"><path className="ico-line" d="M8 12h34v22H23l-9 8v-8H8V12Z"/><path className="ico-line" strokeLinejoin="round" d="M22 24h34v22h-9l1 8-12-8H22V24Z"/></svg>,
 <svg key="screens" viewBox="0 0 64 64" aria-hidden="true"><rect className="ico-line" x="8" y="12" width="36" height="26" rx="2"/><path className="ico-line" strokeLinecap="round" d="M20 44h12"/><rect className="ico-mask ico-line" x="38" y="24" width="16" height="26" rx="2"/><path className="ico-line" strokeLinecap="round" d="M44 44h4"/></svg>,
 <svg key="quality" viewBox="0 0 64 64" aria-hidden="true"><path className="ico-fill ico-line ico-thin" strokeLinejoin="round" d="M16 22 32 8l16 14-16 34-16-34Z"/></svg>,
 <svg key="growth" viewBox="0 0 64 64" aria-hidden="true"><rect className="ico-fill" x="10" y="34" width="9" height="20"/><rect className="ico-fill" x="24" y="24" width="9" height="30"/><rect className="ico-fill" x="38" y="14" width="9" height="40"/><path className="ico-line" strokeLinecap="round" strokeLinejoin="round" d="M10 30 24 18 34 26 52 8"/><path className="ico-line" strokeLinecap="round" strokeLinejoin="round" d="M42 8h10v10"/></svg>,
];
export default function About(){return <main><VideoHero video="/videos/video-2.mp4" kicker="ABOUT FORTY PIXELS" title="Small enough to stay close. Experienced enough to see the whole system." copy="We are a design and development studio helping founders, new businesses and growing brands build a confident digital presence."/>
<section className="story section-pad" data-nav-theme="light"><Eyebrow index="01" label="Who we are"/><div className="story-layout"><h2><Words>We make ambitious digital work feel understandable.</Words></h2><div data-reveal><p>Many clients arrive with an outdated website, a product idea that is difficult to explain or a digital experience that no longer matches the business.</p><p>We make the path forward clear. Strategy, design and development stay connected, communication remains direct and every major decision is visible before it becomes expensive.</p></div></div></section>
<section className="mission section-pad" data-nav-theme="lime"><Eyebrow index="02" label="Our mission"/><h2><Words>Give growing businesses access to digital quality without agency complexity.</Words></h2><p data-reveal>Clean thinking. Fast delivery. A collaborative workflow. Work that earns trust and supports long-term growth.</p></section>
<section className="values section-pad" data-nav-theme="light"><Eyebrow index="03" label="Principles behind the work"/><div className="values-grid">{values.map(([t,c],i)=><article key={t} data-reveal><span>0{i+1}</span><div className="values-icon">{valueIcons[i]}</div><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section className="belief section-pad" data-nav-theme="dark"><Eyebrow index="04" label="What clients get" light/><blockquote data-reveal>One focused team, one clear direction and a digital experience built around what the business needs next.</blockquote></section><ContactBand/></main>}
