import type {Metadata} from "next";
import {ContactBand,Eyebrow,VideoHero,Words} from "../components/Sections";
export const metadata:Metadata={title:"About",description:"Forty Pixels is a focused design and development studio for founders and growing businesses."};
const values=[["Effortless clarity","Good design guides people without making them work for the answer."],["Speed with purpose","Moving quickly matters when every decision still supports the goal."],["Direct communication","The people in the conversation are the people doing the work."],["Every screen","Mobile, tablet and desktop are designed as one connected experience."],["Accessible quality","Premium work comes from focus and craft—not unnecessary layers."],["Long-term thinking","A website or product should be able to grow with the business behind it."]];
export default function About(){return <main><VideoHero video="/videos/video-2.mp4" kicker="ABOUT FORTY PIXELS" title="Small enough to stay close. Experienced enough to see the whole system." copy="We are a design and development studio helping founders, new businesses and growing brands build a confident digital presence."/>
<section className="story section-pad" data-nav-theme="light"><Eyebrow index="01" label="Who we are"/><div className="story-layout"><h2><Words>We make ambitious digital work feel understandable.</Words></h2><div data-reveal><p>Many clients arrive with an outdated website, a product idea that is difficult to explain or a digital experience that no longer matches the business.</p><p>We make the path forward clear. Strategy, design and development stay connected, communication remains direct and every major decision is visible before it becomes expensive.</p></div></div></section>
<section className="mission section-pad" data-nav-theme="lime"><Eyebrow index="02" label="Our mission"/><h2><Words>Give growing businesses access to digital quality without agency complexity.</Words></h2><p data-reveal>Clean thinking. Fast delivery. A collaborative workflow. Work that earns trust and supports long-term growth.</p></section>
<section className="values section-pad" data-nav-theme="light"><Eyebrow index="03" label="Principles behind the work"/><div className="values-grid">{values.map(([t,c],i)=><article key={t} data-reveal><span>0{i+1}</span><h3>{t}</h3><p>{c}</p><i/></article>)}</div></section>
<section className="belief section-pad" data-nav-theme="dark"><Eyebrow index="04" label="What clients get" light/><blockquote data-reveal>One focused team, one clear direction and a digital experience built around what the business needs next.</blockquote><div className="belief-meta"><span>FOUNDED IN COLOMBO</span><span>WORKING WORLDWIDE</span></div></section><ContactBand/></main>}
