"use client";

import {useEffect,useRef,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import Lenis from "lenis";

const packages=[
 {no:"01",name:"Launch Page",audience:"Founders & new businesses",copy:"A focused, high-converting one-page website built to launch fast and make your first impression count.",points:["Strategy & wireframe","Custom responsive design","Fast, SEO-ready build","Launch support"],tone:"lime"},
 {no:"02",name:"Brand Website",audience:"Growing service brands",copy:"A clear, structured website that communicates your value, earns trust and turns attention into enquiries.",points:["Up to 7 key pages","Conversion-led UX","CMS & analytics","Responsive development"],tone:"dark"},
 {no:"03",name:"Commerce Lite",audience:"Ambitious online stores",copy:"A refined commerce experience that is simple to operate, effortless to browse and ready to sell.",points:["Product architecture","Secure checkout","Inventory workflow","Launch optimisation"],tone:"white"},
 {no:"04",name:"Scalable Build",audience:"Startups & platforms",copy:"A flexible website or web application engineered around your product, operations and next stage of growth.",points:["Product discovery","Custom UX system","Scalable engineering","Ongoing partnership"],tone:"grid"}
];
const projects=[
 {tag:"FOOD DELIVERY",title:"OYO Eats",type:"Custom delivery platform",url:"oyoeats.lk",logo:"/logos/oyo-eats.png",tone:"green"},
 {tag:"FINTECH",title:"Taanz",type:"Accounting services platform",url:"taanzoutsourcing.com",logo:"/logos/taanz.png",tone:"blue"},
 {tag:"E-COMMERCE",title:"Nuzii",type:"Fashion commerce experience",url:"nuzii.co",logo:"/logos/nuzi.png",tone:"rose"}
];
const steps=[["01","Discovery call","We learn your goals, audience and vision."],["02","Business deep dive","We uncover what makes your brand valuable."],["03","Design phase","We shape an original experience around your story."],["04","Feedback rounds","You review, we refine and lock the direction."],["05","Development","We build a fast, responsive website."],["06","Launch & support","We go live and stay close as you grow."]];
const Arrow=()=> <span className="arrow" aria-hidden />;
function Reveal({children}:{children:string}){return <span className="reveal" aria-label={children}>{children.split(" ").map((w,i)=><span className="clip" aria-hidden key={i}><span className="word">{w}&nbsp;</span></span>)}</span>}
function Shapes({kind="rings"}:{kind?:string}){return <div className={`shapes ${kind}`} aria-hidden>{[0,1,2,3,4].map(i=><i key={i}/>)}</div>}

export function HomeExperience(){
 const root=useRef<HTMLDivElement>(null); const [menu,setMenu]=useState(false); const [active,setActive]=useState(0);
 useEffect(()=>{if(!root.current)return; gsap.registerPlugin(ScrollTrigger); const reduce=matchMedia("(prefers-reduced-motion:reduce)").matches; const lenis=new Lenis({lerp:.1,smoothWheel:!reduce}); lenis.on("scroll",ScrollTrigger.update); const tick=(t:number)=>lenis.raf(t*1000); gsap.ticker.add(tick); gsap.ticker.lagSmoothing(0);
 const ctx=gsap.context(()=>{
  const pre=document.querySelector<HTMLElement>(".preloader"); const seen=sessionStorage.getItem("fp-loader")==="1";
  if(reduce||seen){pre?.remove()}else if(pre){lenis.stop();sessionStorage.setItem("fp-loader","1");const count={n:0};gsap.timeline({defaults:{ease:"power3.inOut"}})
   .to(count,{n:100,duration:4.5,ease:"power1.inOut",onUpdate:()=>{const n=Math.round(count.n);document.querySelectorAll("[data-load]").forEach(e=>e.textContent=`${n}%`);pre.style.setProperty("--load",`${n}%`) }},0)
   .to(".loader-left i",{x:(i)=>[0,17,-17,31,-31][i],stagger:.05,duration:.5,yoyo:true,repeat:3},0)
   .to(".loader-right i",{x:(i)=>54-i*14,y:(i)=>i*5,rotation:45,stagger:.08,duration:.5,yoyo:true,repeat:3},.5)
   .set("[data-load]",{innerText:"READY"}).to(".loader-lime",{width:0,duration:1.4}).to(".loader-bottom",{yPercent:100,autoAlpha:0,stagger:.1,duration:.5},"<+.1").to(".loader-pattern",{yPercent:100,duration:.9},">-.1").to({}, {duration:.4})
   .to(pre,{yPercent:-100,duration:1.4,ease:"power4.inOut"}).fromTo(".hero-video",{scale:1.4},{scale:1,duration:2.2,ease:"power3.out"},"<").fromTo(".hero-scrim",{opacity:.9},{opacity:.25,duration:2.2},"<").add(()=>{lenis.start();pre.remove()},"<+1.3")}
  gsap.utils.toArray<HTMLElement>(".reveal").forEach(el=>gsap.fromTo(el.querySelectorAll(".word"),{yPercent:110},{yPercent:0,duration:1.15,stagger:.045,ease:"power4.out",scrollTrigger:{trigger:el,start:"top 86%",toggleActions:"play none none reverse"}}));
  gsap.utils.toArray<HTMLElement>("[data-reveal]").forEach((el,i)=>gsap.fromTo(el,{y:72,autoAlpha:0},{y:0,autoAlpha:1,duration:1.05,delay:(i%3)*.06,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 90%",toggleActions:"play none none reverse"}}));
  document.querySelectorAll<HTMLElement>("[data-fill]").forEach(el=>gsap.fromTo(el.querySelectorAll("span"),{opacity:.18},{opacity:1,stagger:.08,ease:"none",scrollTrigger:{trigger:el,start:"top 80%",end:"bottom 55%",scrub:true}}));
  gsap.to(".hero-dark",{opacity:.95,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom 20%",scrub:true}});
  gsap.utils.toArray<HTMLElement>("[data-parallax]").forEach(el=>gsap.fromTo(el,{yPercent:18},{yPercent:-18,ease:"none",scrollTrigger:{trigger:el.parentElement,start:"top bottom",end:"bottom top",scrub:true}}));
  gsap.utils.toArray<HTMLElement>(".motion-card").forEach(card=>{const s=card.querySelectorAll(".shapes i");const tl=gsap.timeline({paused:true}).fromTo(s,{scale:.62,x:0,y:0,rotation:0},{scale:1,x:i=>(i-2)*24,y:i=>Math.abs(i-2)*8,rotation:i=>(i-2)*12,stagger:.05,duration:.65,ease:"power4.out"});ScrollTrigger.create({trigger:card,start:"center bottom",end:"bottom top",animation:tl,toggleActions:"play reverse play reverse"});card.onmouseenter=()=>tl.progress()===1&&void gsap.to(s,{x:i=>(i-2)*18,duration:.3,stagger:.03});card.onmouseleave=()=>tl.progress()===1&&void gsap.to(s,{x:i=>(i-2)*24,duration:.3,stagger:.03})});
  gsap.utils.toArray<HTMLElement>(".package-card").forEach((card,i)=>ScrollTrigger.create({trigger:card,start:"top center",end:"bottom center",onEnter:()=>setActive(i),onEnterBack:()=>setActive(i)}));
 },root); return()=>{ctx.revert();ScrollTrigger.getAll().forEach(t=>t.kill());gsap.ticker.remove(tick);lenis.destroy()}},[]);
 useEffect(()=>{document.body.classList.toggle("menu-open",menu);return()=>document.body.classList.remove("menu-open")},[menu]);
 const filled="A senior, focused team for brands that value clarity, craft and measurable growth. From first sketch to live product, every detail is designed to do real work.".split(" ");
 return <div ref={root} className="site">
  <div className="preloader"><div className="loader-cell loader-lime"><span>// FORTY PIXELS</span><strong data-load>0%</strong></div><div className="loader-cell loader-pattern"><span>// BUILDING CLARITY...</span><strong data-load>0%</strong></div><div className="loader-cell loader-bottom"><p>DESIGNING THE<br/>RIGHT EXPERIENCE...</p><div className="loader-shape loader-left">{[0,1,2,3,4].map(i=><i key={i}/>)}</div></div><div className="loader-cell loader-bottom"><p>ENGINEERING FOR<br/>REAL GROWTH...</p><div className="loader-shape loader-right">{[0,1,2,3].map(i=><i key={i}/>)}</div></div></div>
  <header className="nav"><a className="brand" href="#top"><img src="/brand/logo.png" alt="Forty Pixels"/></a><nav><a href="#services">Services</a><a href="#work">Work</a><a href="#process">Process</a><a href="#about">About</a></nav><a className="nav-cta magnetic" href="#contact">Start a project <Arrow/></a><button className="menu-toggle" onClick={()=>setMenu(true)}>Menu</button></header>
  <div className={`menu-panel ${menu?"open":""}`}><div className="menu-head"><img src="/brand/logo.png" alt=""/><button onClick={()=>setMenu(false)}>Close ×</button></div><div className="menu-links">{[["Services","services"],["Work","work"],["Process","process"],["About","about"],["Contact","contact"]].map(([label,id],i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}><small>0{i+1}</small>{label}<Arrow/></a>)}</div><div className="menu-foot"><span>hello@fortypixels.com</span><span>Colombo · Worldwide</span></div></div>
  <main>
   <section className="hero" id="top"><video className="hero-video" autoPlay muted loop playsInline poster="https://cdn.coverr.co/videos/coverr-coding-on-a-laptop-2116/thumbnail?width=1920"><source src="https://cdn.coverr.co/videos/coverr-coding-on-a-laptop-2116/1080p.mp4" type="video/mp4"/></video><div className="hero-scrim"/><div className="hero-dark"/><div className="hero-kicker"><span>WEB DESIGN & DEVELOPMENT</span></div><div className="hero-content"><h1><Reveal>Clarity over complexity.</Reveal></h1><p><Reveal>Premium digital experiences for ambitious brands.</Reveal></p><a href="#work" className="round-link magnetic"><span>Explore<br/>our work</span><Arrow/></a></div><div className="scroll-cue"><span>SCROLL TO EXPLORE</span><i/></div></section>
   <section className="intro section" id="about"><div className="label"><span>01</span><span>ABOUT FORTY PIXELS</span></div><div className="split"><h2 data-fill>{filled.map((w,i)=><span key={i}>{w} </span>)}</h2><div className="side" data-reveal><p>Modern web design for startups and growing brands. We create clean, responsive websites that look premium, feel effortless and convert.</p><a className="text-link" href="#contact">Meet your digital partner <Arrow/></a></div></div><div className="cap-grid"><article className="motion-card cap" data-reveal><div><span>01</span><h3>Strategy & design</h3><p>Positioning, structure and visual systems that make your value instantly clear.</p></div><Shapes/></article><article className="motion-card cap inverse" data-reveal><div><span>02</span><h3>Development</h3><p>Fast, responsive engineering built to perform across every screen and interaction.</p></div><Shapes kind="tiles"/></article><article className="motion-card cap lime" data-reveal><div><span>03</span><h3>Growth & support</h3><p>Focused iteration that keeps your website working harder over time.</p></div><Shapes kind="orbit"/></article></div></section>
   <section className="impact section"><div className="label light"><span>02</span><span>RESULTS, NOT DECORATION</span></div><div className="split"><h2><Reveal>Built to move business forward.</Reveal></h2><p data-reveal>Every decision has a purpose: sharpen the message, remove friction and make the next action obvious.</p></div><div className="stats"><article><strong>05<span>–</span>42</strong><p>days from focused launch page to scalable product build</p></article><article><strong>100<span>%</span></strong><p>custom responsive experiences—never recycled templates</p></article><article><strong>01<span>:</span>01</strong><p>direct collaboration with the people designing and building</p></article></div></section>
   <section className="services section" id="services"><div className="label"><span>03</span><span>SERVICES</span></div><div className="split"><h2><Reveal>Choose the right build.</Reveal></h2><p data-reveal>Clear scope. Honest timelines. Every engagement designed around the stage your business is actually in.</p></div><div className="package-layout"><aside className="rail"><span>0{active+1}</span><div><i style={{height:`${(active+1)*25}%`}}/></div><span>04</span></aside><div className="package-list">{packages.map((p,pi)=><article className={`package-card ${p.tone}`} key={p.name}><div className="package-copy"><div className="package-meta"><span>// {p.no}</span><span>{p.audience}</span></div><h3>{p.name}</h3><p>{p.copy}</p><a href="#contact" className="text-link">Discuss this package <Arrow/></a></div><div className="package-visual"><Shapes kind={pi===1?"tiles":pi>1?"orbit":"rings"}/><ul>{p.points.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ul></div></article>)}</div></div></section>
   <section className="work section" id="work"><div className="label light"><span>04</span><span>SELECTED WORK</span></div><div className="work-head"><h2><Reveal>Made for the real world.</Reveal></h2><a href="#contact" className="text-link">Build something with us <Arrow/></a></div><div className="work-grid">{projects.map((p,i)=><article className={`work-card ${p.tone}`} key={p.title} data-reveal><div className="work-meta"><span>0{i+1}</span><span>{p.tag}</span></div><div className="work-window" data-parallax><div className="browser-bar"><i/><i/><i/><span>{p.url}</span></div><img src={p.logo} alt={`${p.title} logo`}/></div><div className="work-info"><div><h3>{p.title}</h3><p>{p.type}</p></div><span className="work-arrow"><Arrow/></span></div></article>)}</div></section>
   <section className="process section" id="process"><div className="label"><span>05</span><span>HOW WE WORK</span></div><div className="split"><h2><Reveal>Your website journey, simplified.</Reveal></h2><p data-reveal>Easy, transparent and collaborative from the first conversation to launch day.</p></div><div className="steps">{steps.map(([n,t,c])=><article key={n} data-reveal><span>{n}</span><h3>{t}</h3><p>{c}</p><i/></article>)}</div></section>
   <section className="trust section"><div className="label"><span>06</span><span>TRUSTED BY BUILDERS</span></div><div className="marquee"><div>{[...projects,...projects].map((p,i)=><span key={i}><img src={p.logo} alt={i<3?p.title:""}/><b>×</b></span>)}</div></div><blockquote data-reveal>“Forty Pixels made the complex feel simple. The process was clear, the details were thoughtful, and the result finally feels like us.”</blockquote><div className="quote-by"><span>FOUNDER, GROWING BRAND</span><span>★★★★★</span></div></section>
   <section className="contact section" id="contact"><div className="contact-media"><video autoPlay muted loop playsInline><source src="https://cdn.coverr.co/videos/coverr-coding-on-a-laptop-2116/720p.mp4" type="video/mp4"/></video><div/></div><div className="contact-copy"><span className="eyebrow">REPLIES WITHIN ONE WORKING DAY</span><h2><Reveal>Ready to make your website matter?</Reveal></h2><p data-reveal>Tell us what you’re building. We’ll ask the right questions, recommend the right path and give you a clear next step.</p><form data-reveal onSubmit={e=>e.preventDefault()}><label><span>Your name</span><input required placeholder="Jane Smith"/></label><label><span>Work email</span><input required type="email" placeholder="jane@company.com"/></label><label className="full"><span>What are you looking to build?</span><textarea rows={3} placeholder="A little about your project, goals and timing..."/></label><button>Start the conversation <Arrow/></button></form></div></section>
  </main>
  <footer><div className="footer-top"><a className="footer-brand" href="#top">FORTY<br/>PIXELS<span>.</span></a><p>Premium web design and development<br/>for startups and growing brands.</p><a className="footer-email" href="mailto:hello@fortypixels.com">hello@fortypixels.com <Arrow/></a></div><div className="footer-links"><div><span>PAGES</span><a href="#services">Services</a><a href="#work">Work</a><a href="#process">Process</a><a href="#about">About</a></div><div><span>SOCIAL</span><a href="#">LinkedIn <Arrow/></a><a href="#">Instagram <Arrow/></a><a href="#">X / Twitter <Arrow/></a></div><div><span>LOCATION</span><p>Colombo, Sri Lanka<br/>Working worldwide</p></div></div><div className="footer-bottom"><span>© 2026 FORTY PIXELS</span><span>PRIVACY</span><a href="#top">BACK TO TOP <span className="text-arrow" aria-hidden /></a></div></footer>
 </div>
}
