import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {ContactBand,Eyebrow,projectData,ProjectKey,Words} from "../../components/Sections";
export function generateStaticParams(){return Object.keys(projectData).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projectData[slug as ProjectKey];if(!p)return{};return{title:`${p.name} case study`,description:p.summary}}
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projectData[slug as ProjectKey];if(!p)notFound();const experience=slug==="noora"?[["Structure","The catalog is organised the way a shopper browses modest fashion — by occasion and piece, so everyday abayas and occasional wear each have a clear path."],["Identity","A restrained, editorial visual language in terms of generous space, quiet type, and photography given room to lead. The clothes carry the page."],["Performance","Orders flow into Clickom and stock stays synced by product ID, so the storefront runs itself in the background — no double entry, no overselling."]]:[["Structure","Content organised around the questions users need answered before moving forward."],["Identity","A visual language that supports the character of the business without adding noise."],["Performance","Responsive engineering built to keep the experience fast and dependable."]];return <main className={`case-study case-${slug}`}>
<section className={`case-hero ${p.tone}`} id="top" data-nav-theme="light"><div className="case-kicker"><span>{"// CASE STUDY"}</span><span>{p.tag}</span><span>{p.url}</span></div><h1><Words>{p.name}</Words></h1><p data-reveal>{p.summary}</p><a href={`https://${p.url}`} className="case-site-link" target="_blank" rel="noopener noreferrer">Visit live website <span aria-hidden>↗</span></a><div className="case-browser" data-reveal><div><i/><i/><i/><small>{p.url}</small></div><img className={p.name==="Forte Clinical Laboratories"?"case-logo-dark":""} src={p.logo} alt={`${p.name} logo`}/></div></section>
<section className="case-overview section-pad" data-nav-theme="light"><Eyebrow index="01" label="Project overview"/><div className="case-copy"><div><span>THE CHALLENGE</span><h2><Words>{p.challenge}</Words></h2></div><div><span>THE RESPONSE</span><p data-reveal>{p.solution}</p></div></div></section>
{p.shots.length>0&&<section className="case-gallery section-pad" data-nav-theme="light"><h2><Words>A closer look inside the build.</Words></h2><div className="case-gallery-grid">{p.shots.map((src,i)=><figure key={src} data-reveal><img src={src} alt={`${p.name} website screenshot ${i+1}`}/></figure>)}</div></section>}
<section className={`case-results section-pad ${p.tone}`} data-nav-theme={p.tone==="lime"?"light":"dark"}><Eyebrow index="02" label="Recorded results" light={p.tone!=="lime"}/><div className="case-metrics">{p.metrics.map(([n,l])=><article key={l}><strong>{n}</strong><p>{l}</p></article>)}</div></section>
<section className="case-system section-pad" data-nav-theme="dark"><Eyebrow index="03" label="The experience" light/><h2><Words>A clearer path from first impression to meaningful action.</Words></h2><div className="system-grid">{experience.map(([title,copy],index)=><article key={title}><span>{String(index+1).padStart(2,"0")} ·</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><ContactBand title="Need a result shaped around your business?"/></main>}
